# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064a91845081f822a0f04e1a276e74b54b6fa34801d57e93bf674e9354df85937bad9ed817fb6ff40a9f7ecae6e05d8cf2029bcdba8ab0b991e115cd8cf022b2

test:
  secret_key_base: ed724c2fafcab3b2b8ac0c137655f9506b7c4f659447b41a28c76e168ce57ac96ab89b65d706e151ea799f677cd524476f3a9897a202cd2e39c19a37fb85d73a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
